#
# For documentation: https://docs.codecov.io/docs/codecovyml-reference
# Twisted settings: https://codecov.io/gh/twisted/twisted/settings/yaml
#
# We want 100% coverage for new patches to make sure we are always increasing
# the coverage.
#
codecov:
  require_ci_to_pass: yes
  notify:
    # We have at least 10 builds in GitHub Actions and 12 in Azure
    # and lint + mypy + docs + ReadTheDocs
    after_n_builds: 15
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  status:
    patch:
      default:
        # New code should have 100% CI coverage as the minimum
        # quality assurance measurement.
        # If there is a good reason for new code not to have coverage,
        # add inline pragma comments.
        target: 100%
    project:
      default:
        # Allow for a bit of slack in overall project report.
        # As long as the patch is 100% the PR should be ok.
        # We report coverage even on errors.
        # So a run on trunk might fail and during the failure process will
        # exercise a different code branch (ex timeout errors).
        # This code branch is reported at the end of the run.
        # Future test runs will not trigger the error and the error handling
        # code branch is not called, and if no other tests is touching that
        # branch we are left with overall reduced code coverage.
        threshold: 0.02%


# We don't want to receive general PR comments about coverage.
# We have the commit status checks and that should be enough.
# See https://docs.codecov.io/docs/pull-request-comments
comment: false

# See https://docs.codecov.io/docs/github-checks
github_checks:
  # We want codecov to send inline PR comments for missing coverage.
  annotations: true
