#
# For documentation: https://docs.codecov.io/docs/codecovyml-reference
# Twisted settings: https://codecov.io/gh/twisted/twisted/settings/yaml
#
# We want 100% coverage for new patches to make sure we are always increasing
# the coverage.
#
codecov:
  require_ci_to_pass: yes
  notify:
    # We have at least 10 builds in GitHub Actions and 12 in Azure
    # and lint + mypy + docs + ReadTheDocs
    after_n_builds: 15
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  status:
    patch:
      default:
        target: 100%
    project:
      default:
        threshold: 0.02%


# We don't want to receive general PR comments about coverage.
# We have the commit status checks and that should be enough.
# See https://docs.codecov.io/docs/pull-request-comments
comment: false

# See https://docs.codecov.io/docs/github-checks
github_checks:
  # We want codecov to send inline PR comments for missing coverage.
  annotations: true
