name: 'Run tox environments'
description: 'Shared steps for running tox.'
runs:
  using: 'composite'
  steps:

  - name: Install dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip tox
      tox --notest

  - name: Test
    shell: bash
    run: |
      python --version
      tox -q
