parameters:

- name: platform
  type: string
  values:
  - macos
  - windows

- name: pythonVersion
  type: string
  values:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'

- name: windowsReactor
  type: string
  default: select
  values:
  - select
  - iocp

- name: allowFailure
  type: boolean
  default: false

steps:
- checkout: self
  clean: true
  fetchDepth: 2

- task: UsePythonVersion@0
  displayName: "Use Python ${{ parameters.pythonVersion }}"
  inputs:
    versionSpec: "${{ parameters.pythonVersion }}"

- script: |
   python --version
   python -c "import sys; print(sys.prefix)"
   python -c "import sys; print(sys.exec_prefix)"
   python -c "import sys; print(sys.executable)"
   python -c "import struct; print(struct.calcsize('P') * 8)"
   python -c "print('\nENVIRONMENT VARIABLES\n=====================\n\n')"
   python -c "import os; [ print(e,v) for (e,v) in os.environ.items() ]"
  displayName: 'Get Python Information'

- script: 'python -m pip install -U pip setuptools tox coveralls pyyaml'
  displayName: 'Update pip & install tox'

- ${{ if eq(parameters.platform, 'macos') }}:
  - script: 'python -m tox -e alldeps-withcov-posix'
    displayName: 'Run tests'
    continueOnError: ${{ parameters.allowFailure }}
    env:
      TRIAL_ARGS: "-j 4"

- ${{ if eq(parameters.platform, 'windows') }}:
  - script: 'python -m tox -e alldeps-withcov-windows'
    displayName: 'Run tests'
    continueOnError: ${{ parameters.allowFailure }}
    env:
      TWISTED_REACTOR: ${{ parameters.windowsReactor }}

- bash: |
    bash <(curl -s https://codecov.io/bash) -X search -X gcov -f coverage.xml -v -n "${{ parameters.platform }}-${{ parameters.pythonVersion }}-alldeps-withcov"
  displayName: 'Report codecov.io'

- bash: |
    export CIRCLE_BRANCH=$BUILD_SOURCEBRANCH
    python -m coveralls
  displayName: 'Report coveralls'
  env:
    CIRCLECI: 1
    CIRCLE_BUILD_NUM: $(Build.BuildNumber)
    COVERALLS_REPO_TOKEN: 'JFDTIRUVOQ8jCM3zcajrZALlpKXyiXGAX'
